language: node_js
node_js:
  - 8
  - 7
  - 6
before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
script:
  - yarn run test
  - yarn run test-smoke-ci
after_success:
  - yarn run coveralls
cache:
  yarn: true
  directories:
    - /home/travis/.cypress/Cypress
