language: node_js
sudo: required
node_js:
  - 10
  - 8
  # - 6
before_install:
  - sudo sysctl fs.inotify.max_user_watches=524288
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
install: 'yarn install --ignore-engines'
script:
  # Test source (with cross-package coverage)
  - yarn src
  - yarn type-check
  - yarn lint
  - yarn test:coverage --maxWorkers=2
  - yarn codecov

  # Test build
  - yarn dist
  - yarn build
  - yarn export
  - yarn test:ci
cache:
  yarn: true
  directories:
    - ~/.cache/Cypress
