language: node_js
sudo: required
node_js:
  - 10
  - 8
  - 6
before_install:
  - sudo sysctl fs.inotify.max_user_watches=524288
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
install: 'yarn install --ignore-engines'
script:
  # Building upfront because some react-cosmos/server unit tests require
  # react-cosmos-playground to be built
  - yarn build
  # Test source (with cross-package coverage)
  - yarn link-entries src
  - yarn flow
  - yarn lint
  - yarn test:unit --maxWorkers=2
  # Test build
  - yarn link-entries dist
  - yarn start & yarn test:e2e
after_success:
  # Report coverage
  - yarn codecov
cache:
  yarn: true
  directories:
    - /home/travis/.cypress/Cypress
