# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  node-base: &node-base
    docker:
      # https://docs.cypress.io/guides/guides/continuous-integration.html#Example-circle-yml-v2-config-file-with-yarn
      # https://github.com/cypress-io/cypress-docker-images
      - image: cypress/base
    working_directory: ~/app
    parallelism: 1
    steps:
      # Clone repository to working directory
      - checkout

      # Download and cache dependencies
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn install --ignore-engines
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            # Cache both yarn and Cypress
            - ~/.cache

      # Test source (with cross-package coverage)
      - run: yarn src
      - run: yarn lint
      - run: yarn test:coverage --maxWorkers=2
      - run: yarn codecov

      # Test build
      - run: yarn dist
      - run: yarn build
      - run: yarn start & yarn test:smoke

      - store_artifacts:
          path: /root/app/cypress/screenshots
      - store_artifacts:
          path: /root/app/cypress/videos

  node-v6:
    <<: *node-base
    docker:
      - image: cypress/base:6
  node-v8:
    <<: *node-base
    docker:
      - image: cypress/base:8
  node-v10:
    <<: *node-base
    docker:
      - image: cypress/base:10

# https://github.com/teppeis-sandbox/circleci2-multiple-node-versions/tree/yarn-with-test-report
workflows:
  version: 2
  node-multi-build:
    jobs:
      # Limitting CircleCI usage
      # - node-v6
      # - node-v8
      - node-v10
